# Page settings
baseurl = "localhost:1313"
title = "CS50 Manchester"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]
  custom_css = ["css/custom1.css"]

  # Meta
  author = "CS50 Manchester"
  description = "CS50 Manchester 2017 - a hackathon in association with Harvad 25 March 2017"
  email = "hristeaanais@gmail.com"
  # Navigation
  [params.navigation]
    brand = "CS50 Manchester"
    home = "Home"
    faq = "FAQ"
    schedule = "Schedule"
    sponsors = "Sponsors"
    chart = "Attendance"
    location = "Location"
    contact = "Get In Touch"

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = " "
    #  name = " "
    #  weight = 10

  # Hero section
  [params.hero]
    title = "25 March 2017 <br> Manchester, England"
    subtitle = "Brought to you by Harvard <br> in association with HackSoc Manchester."
    url = "#"

  # FAQ section
  [params.faq]
    enable = true
    title = "FAQ"

    [[params.faq.item]]
      title = "Who can get a ticket?"
      description = "All enrolled students over 18 and those who graduated last year."
      icon = "icon-graduation"


    [[params.faq.item]]
      title = "Are tickets free?"
      description = "Only for students from Manchester. Otherwise, they cost £50... Including a t-shirt ;)"
      icon = "icon-wallet"

    [[params.faq.item]]
      title = "What if I study outside the UK?"
      description = "You are still welcome to join us! However, we cannot offer travel scholarships."
      icon = "icon-plane"

    [[params.faq.item]]
      title = "I haven't coded much. Should I come?"
      description = "Hackathons are for beginners. This one in particular. The CS50 course at Harvard is meant for people with little to no prior experience. You'll get the chance to meet other hackers and learn with and from each other. And also, the Harvard team will be there to assist you."
      icon = "icon-briefcase"

    [[params.faq.item]]
      title = "What can I expect from CS50?"
      description = "The CS50 Hackathon is an epic all-nighter during which you can take your first steps towards becoming a programmer. You can definetly expect to learn A LOT by coming here."
      icon = "icon-magic-wand"

    [[params.faq.item]]
      title = "What should I bring?"
      description = "Bring your laptop, phone and chargers. Other things to consider: spare clothes, adapters, hardware and a sleeping bag. Oh, and don't forget your enthusiasm! We are going to provide you with all the food, drinks, sleeping areas and swag that you will need."
      icon = "icon-basket-loaded"

    [[params.faq.item]]
      title = "Who owns my IP/code/idea?"
      description = "You own all the rights to your intellectual property. We won't claim any right over anything made during this event."
      icon = "icon-bulb"

  # Schedule section
  [params.schedule]
    enable = false
    title = "Schedule"

    [[params.schedule.friday]]
      time = "18:00"
      name = "Registration opens"

    [[params.schedule.friday]]
      time = "19:00"
      name = "Dinner"

    [[params.schedule.friday]]
      time = "20:30"
      name = "Opening ceremony"

    [[params.schedule.friday]]
      time = "22:00"
      name = "Hacking starts<br>Team forming session"


    [[params.schedule.saturday]]
      time = "00:00"
      name = "Midnight snack"

    [[params.schedule.saturday]]
      time = "08:00"
      name = "Breakfast"

    [[params.schedule.saturday]]
      time = ""
      name = "-- Workshops --"

    [[params.schedule.saturday]]
      time = "13:00"
      name = "Lunch"

    [[params.schedule.saturday]]
      time = ""
      name = "-- Workshops --"

    [[params.schedule.saturday]]
      time = "19:00"
      name = "Dinner"

    [[params.schedule.saturday]]
      time = "21:00"
      name = "MLH event"


    [[params.schedule.sunday]]
      time = "00:00"
      name = "Midnight snack"

    [[params.schedule.sunday]]
      time = "08:00"
      name = "Breakfast"

    [[params.schedule.sunday]]
      time = "10:00"
      name = "Hacking ends"

    [[params.schedule.sunday]]
      time = "11:00"
      name = "Judging starts"

    [[params.schedule.sunday]]
      time = "13:00"
      name = "Lunch"

    [[params.schedule.sunday]]
      time = "14:00"
      name = "Final presentations"

    [[params.schedule.sunday]]
      time = "16:00"
      name = "Closing ceremony"

    [[params.schedule.sunday]]
      time = "17:00"
      name = "End of the event"


  # Sponsors section
  [params.sponsors]
    enable = false
    enPlat = false
    enHard = true
    enTrac = false
    enGold = false
    enSilv = true
    enBron = true
    enPart = true
    title = "Sponsors"
    description = "They made it possible!"

    [[params.sponsors.platinum]]
      img = "work_1.jpg"
      alt = "Image2"

    [[params.sponsors.hardware]]
      img = "google.png"
      alt = "Google"
      link = "https://get.google.com/tango/"

    [[params.sponsors.track]]
      img = "work_1.jpg"
      alt = "Image2"

    [[params.sponsors.track]]
      img = "work_1.jpg"
      alt = "Image2"

    [[params.sponsors.gold]]
      img = "work_1.jpg"
      alt = "Image2"

    [[params.sponsors.silver]]
      img = "twilio.png"
      alt = "Twilio"
      link = "https://www.twilio.com/"

    [[params.sponsors.bronze]]
      img = "codethink.png"
      alt = "codethink"
      link = "https://www.codethink.co.uk/"

    [[params.sponsors.bronze]]
      img = "noma.png"
      alt = "noma"
      link = "http://www.noma-manchester.com"

    [[params.sponsors.partner]]
      img = "monzo.png"
      alt = "monzo"
      link = "https://monzo.com/"

  # Chart section
  [params.chart]
    enable = false
    title = "Registered"

  # Location section
  [params.location]
    enable = true
    map = true
    title = "Location"
    description = "Renold Building, Altrincham Street, M1 7JA, Manchester, UK"

  # Counters section
  [params.counters]
    enable = false
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Hackers Pre-registerd"
      icon = "icon-briefcase"
      from = 0
      to = 148
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Lines of Code"
      icon = "icon-code"
      from = 0
      to = 343409
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Cups of coffee"
      icon = "icon-cup"
      from = 0
      to = 1337
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Sleepless Hours"
      icon = "icon-power"
      from = 0
      to = 420
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable = true
    title = "Get in touch"
    description = "For any question, feedback or sponsorship proposal, feel free to contact us!"

    # Available icons: http://simplelineicons.com/

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Elate Free HTML5. All Rights Reserved. <br>Created by <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> Images: <a href="http://pexels.com/" target="_blank">Pexels</a>, <a href="http://plmd.me/" target="_blank">plmd.me</a> <br>Hugo port by: <a href="https://github.com/saey55" target="_blank">saey55</a> <br> Edited By  <a href="http://hacksoc.com/" target="_blank">HackSoc</a> Dev Team'
