# Page settings
baseurl = "localhost:1313"
title = "CS50 Manchester"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]
  custom_css = ["css/custom1.css"]

  # Meta
  author = "CS50 Manchester"
  description = "CS50 Manchester 2017 - a hackathon in association with Harvad 25 March 2017"
  email = "cristian@hacksoc.com"
  # Navigation
  [params.navigation]
    brand = "CS50 Manchester"
    home = "Home"
    faq = "FAQ"
    schedule = "Schedule"
    sponsors = "Sponsors"
    chart = "Attendance"
    location = "Location"
    video = "This is CS50"

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = " "
    #  name = " "
    #  weight = 10

  # Hero section
  [params.hero]
    title = "25 March 2017 <br> Manchester, England"
    subtitle = "Brought to you by Harvard <br> in association with HackSoc Manchester."
    url = "#"

  # FAQ section
  [params.faq]
    enable = true
    title = "FAQ"

    [[params.faq.item]]
      title = "What is CS50?"
      description = "CS50 is Harvard and Yale Universities' introduction to computer science for concentrators and non-concentrators alike, with or without prior programming experience."
      icon = "icon-graduation"


    [[params.faq.item]]
      title = "Who teaches CS50?"
      description = "The course is taught by professor <a href=\"https://en.wikipedia.org/wiki/David_Malan_(computer_scientist)\"> David J. Malan</a>,<br>you will meet him at the event!<br>Email: malan@harvard.edu"
      icon = "icon-book-open"

    [[params.faq.item]]
      title = "What is a CS50 Hackathon?"
      description = "It's a 5-hour coding session which allows participants to go through the course while having the opportunity to ask questions directly to David J. Malan and CS50's staff. They will also lead a number of walkthroughs and/or seminars throughout the eve.​"
      icon = "icon-calculator"

    [[params.faq.item]]
      title = "I haven’t coded much. Should I come?"
      description = "Absolutely! The course is designed for people who have no prior experience with programming. The hackathon will be the best opportunity to start the course and ask as many questions as possible directly to CS50's staff members. You’ll also get the chance to meet other hackers and learn with and from each other."
      icon = "icon-user-follow"

    [[params.faq.item]]
      title = "Who can get a ticket?"
      description = "Literally everyone! The hackathon assumes no prior experience and is suitable for anyone who wants to learn computer science. "
      icon = "icon-globe-alt"

    [[params.faq.item]]
      title = "Are tickets free?"
      description = "Tickets are free for Manchester students. For everyone else, the ticket costs £50 and it includes an awesome \"I took CS50\" t-shirt. <a href=\"https://www.picatic.com/cs50-hackathon-manchester\">Get your ticket now!</a>"
      icon = "icon-wallet"

    [[params.faq.item]]
      title = "What can I expect from CS50?"
      description = "The CS50 Hackathon is an epic 5-hour event during which you can take your first steps towards becoming a programmer. You can definetly expect to learn A LOT by coming here."
      icon = "icon-magnifier"

    [[params.faq.item]]
      title = "What should I bring?"
      description = "Bring your laptop, phone, chargers and adaptors. Oh, and don’t forget your enthusiasm! We are going to provide you with all the food, drinks and snacks."
      icon = "icon-briefcase"

  # Schedule section
  [params.schedule]
    enable = false
    title = "Schedule"

    [[params.schedule.friday]]
      time = "18:00"
      name = "Registration opens"

    [[params.schedule.friday]]
      time = "19:00"
      name = "Dinner"

    [[params.schedule.friday]]
      time = "20:30"
      name = "Opening ceremony"

    [[params.schedule.friday]]
      time = "22:00"
      name = "Hacking starts<br>Team forming session"


    [[params.schedule.saturday]]
      time = "00:00"
      name = "Midnight snack"

    [[params.schedule.saturday]]
      time = "08:00"
      name = "Breakfast"

    [[params.schedule.saturday]]
      time = ""
      name = "-- Workshops --"

    [[params.schedule.saturday]]
      time = "13:00"
      name = "Lunch"

    [[params.schedule.saturday]]
      time = ""
      name = "-- Workshops --"

    [[params.schedule.saturday]]
      time = "19:00"
      name = "Dinner"

    [[params.schedule.saturday]]
      time = "21:00"
      name = "MLH event"


    [[params.schedule.sunday]]
      time = "00:00"
      name = "Midnight snack"

    [[params.schedule.sunday]]
      time = "08:00"
      name = "Breakfast"

    [[params.schedule.sunday]]
      time = "10:00"
      name = "Hacking ends"

    [[params.schedule.sunday]]
      time = "11:00"
      name = "Judging starts"

    [[params.schedule.sunday]]
      time = "13:00"
      name = "Lunch"

    [[params.schedule.sunday]]
      time = "14:00"
      name = "Final presentations"

    [[params.schedule.sunday]]
      time = "16:00"
      name = "Closing ceremony"

    [[params.schedule.sunday]]
      time = "17:00"
      name = "End of the event"


  # Sponsors section
  [params.sponsors]
    enable = true
    title = "Sponsors"
    description = "They made it possible!"

    [[params.sponsors.partner]]
      img = "harvard.png"
      alt = "Harvard University"
      link = "http://www.harvard.edu/"

    [[params.sponsors.partner]]
      img = "uom.png"
      alt = "The University of Manchester, School of Computer Science"
      link = "http://www.cs.manchester.ac.uk/"

    [[params.sponsors.partner]]
      img = "landing.png"
      alt = "The Landing"
      link = "http://www.thelanding.org.uk/"

    [[params.sponsors.hardware]]
      img = "google.png"
      alt = "Google"
      link = "https://get.google.com/tango/"

  # Chart section
  [params.chart]
    enable = false
    title = "Registered"

  # Location section
  [params.location]
    enable = true
    map = true
    title = "Location"
    description = "The Landing, Blue, MediaCityUK, M50 2ST, Manchester, UK"

  # Counters section
  [params.counters]
    enable = false
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Hackers Pre-registerd"
      icon = "icon-briefcase"
      from = 0
      to = 148
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Lines of Code"
      icon = "icon-code"
      from = 0
      to = 343409
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Cups of coffee"
      icon = "icon-cup"
      from = 0
      to = 1337
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Sleepless Hours"
      icon = "icon-power"
      from = 0
      to = 420
      interval = 50
      speed = 5000

  # video section
  [params.video]
    enable = true
    title = "This is CS50"
    youtubeIframe = "<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/5dFxQRcsKpw\" frameborder=\"0\" allowfullscreen></iframe>"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Elate Free HTML5. All Rights Reserved. <br>Created by <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> Images: <a href="http://pexels.com/" target="_blank">Pexels</a>, <a href="http://plmd.me/" target="_blank">plmd.me</a> <br>Hugo port by: <a href="https://github.com/saey55" target="_blank">saey55</a> <br> Edited By  <a href="http://hacksoc.com/" target="_blank">HackSoc</a> Dev Team'
